# Default Agent Character Sheet
# This file demonstrates the complete character sheet configuration system

id = "550e8400-e29b-41d4-a716-446655440000"
name = "Default Agent"
version = "1.0.0"
description = "Default character sheet with SurrealDB configuration"
created_at = "2025-01-19T12:00:00Z"
updated_at = "2025-01-19T12:00:00Z"
active = true

[database_config]
primary_db = "SurrealRocks"
fallback_db = "LibSQL"
data_path = "./data/agent.db"
memory_limit_mb = 512
max_connections = 10
enable_encryption = false
backup_enabled = true

[secrets]
encryption_key = "optional-encryption-key-32-chars"

[secrets.api_keys]

[secrets.wallets]

[secrets.credentials]

[secrets.certificates]

[mcp_servers]
default_timeout_seconds = 30
max_concurrent_connections = 5
retry_attempts = 3
health_check_interval_seconds = 60

[mcp_servers.servers]

[templates]
default_language = "en"
template_engine = "Handlebars"

[templates.prompt_templates]

[templates.response_templates]

[templates.workflow_templates]

[knowledge]
vector_search_enabled = false
chunk_size = 1000
overlap_size = 200
indexing_strategy = "FullText"

[knowledge.knowledge_bases]

[personality]
decision_making = "Analytical"

[personality.big_five]
openness = 0.7
conscientiousness = 0.8
extraversion = 0.6
agreeableness = 0.7
neuroticism = 0.3

[personality.communication_style]
formality = "Neutral"
verbosity = "Moderate"
emotion_expression = "Moderate"
humor_level = "Subtle"
technical_depth = "Intermediate"

[personality.emotional_profile]
default_mood = 0.6
emotional_volatility = 0.4
empathy_level = 0.7
stress_tolerance = 0.6
optimism_bias = 0.5

[personality.learning_preferences]
learning_rate = 0.7
memory_retention = 0.8
adaptation_speed = 0.6
curiosity_level = 0.8
risk_tolerance = 0.4

[capabilities]
enabled_capabilities = ["conversation", "memory", "emotion"]

[capabilities.capability_limits]

[capabilities.tool_access]
web_access = false
file_system_access = false
database_access = true
network_access = false
external_apis = false
blockchain_access = false

[capabilities.permissions]
read_permissions = ["memory"]
write_permissions = ["memory"]
execute_permissions = []
admin_permissions = []
restricted_paths = []
allowed_domains = []

[memory_settings]
max_memory_mb = 256
conversation_history_limit = 1000
emotional_memory_days = 30
knowledge_cache_size_mb = 128
auto_cleanup_enabled = true
compression_enabled = true
backup_frequency = "Daily"

[performance]
max_concurrent_tasks = 5
request_timeout_seconds = 30
batch_processing_enabled = true
cache_strategy = "Memory"
optimization_level = "Moderate"

[logging]
log_level = "Info"
log_to_file = true
log_file_path = "./logs/agent.log"
max_log_file_size_mb = 100
log_rotation_count = 5
structured_logging = true
sensitive_data_filtering = true

[security]
encryption_enabled = false
secure_communication = true
certificate_validation = true
access_control_enabled = true
audit_logging = true
data_retention_days = 90
anonymization_enabled = false