[package]
name = "pod-metaplex-core"
version = "0.1.0"
edition = "2021"

[dependencies]
banshee-core = { path = "../core" }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
anyhow = "1.0"
thiserror = "1.0"
tokio = { version = "1.40", features = ["full"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# Solana Agent Kit integration via Node.js runtime
# All Solana operations handled by TypeScript Solana Agent Kit

# Node.js runtime integration for calling Solana Agent Kit
tokio-process = "0.2"
which = "4.4"

# Math
rust_decimal = "1.36"

# Base58 encoding
bs58 = "0.5"

# Borsh serialization
borsh = "1.5"

# HTTP client
reqwest = { version = "0.12", features = ["json"] }

# JSON handling for TypeScript interop (already defined above)

# Image processing for NFTs
image = { version = "0.25", optional = true }

[features]
default = []
image-processing = ["image"]