[package]
name = "banshee-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
banshee-core = { path = "../core" }
# banshee-plugin-bootstrap = { path = "../plugin-bootstrap" }
# banshee-plugin-memory = { path = "../plugin-memory" }

# HTTP client for AI SDK
reqwest = { version = "0.11", features = ["json"] }

# Emotion engine
banshee-emotion-engine = { path = "../../crates/emotion_engine" }

# Core dependencies
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

# Actor framework
actix = { workspace = true }

# Graph database for knowledge graphs
petgraph = "0.6"

# Storage (now required for memory plugin)
sqlx = { workspace = true }
redis = { workspace = true }

# Configuration
config = "0.14"

# Logging
tracing-subscriber = "0.3"

# Environment variables
dotenvy = "0.15"

# TOML parsing
toml = { workspace = true }

# Embedded databases (optional features for different database types)
# Uncomment as needed:
# surrealdb = { version = "2.0", optional = true, features = ["kv-rocksdb"] }
# libsql = { version = "0.5", optional = true, default-features = false, features = ["core"] }
# native_db = { version = "0.7", optional = true }
# redb = { version = "2.1", optional = true }
# duckdb = { version = "1.1", optional = true, features = ["bundled"] }

[features]
default = []
# Optional embedded database features (uncomment when dependencies are added)
# surrealdb-rocks = ["dep:surrealdb"]
# surrealdb-memory = ["dep:surrealdb"]
# libsql = ["dep:libsql"]
# native-db = ["dep:native_db"]
# redb = ["dep:redb"]
# duckdb = ["dep:duckdb"]
# all-databases = ["surrealdb-rocks", "libsql", "native-db", "redb", "duckdb"]

[dev-dependencies]
tokio-test = { workspace = true }
