[package]
name = "banshee-plugin-web3"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
banshee-core = { path = "../core" }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# Solana SDK July 2025 - Latest Available Versions
solana-sdk = "2.3.0"
solana-client = "2.3.0" 
solana-program = "2.3.0"

# SPL Token Program
spl-token = "6.0"
spl-associated-token-account = "4.0"

# Cryptography and encoding
bs58 = "0.5"
bip39 = { version = "2.2", features = ["rand"] }

# Web3 utilities
reqwest = { version = "0.12", features = ["json"] }
anyhow = "1.0"
thiserror = "1.0"
