[package]
name = "banshee-plugin-web3"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
banshee-core = { path = "../core" }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

# TODO: Add Solana Agent Kit dependencies when integrating:
# solana-agent-kit = "0.1"
# @solana/web3.js equivalent for Rust would be:
# solana-sdk = "1.17"
# solana-client = "1.17"
